### ISSUE TITLE
Ground Support: character decoding issue on Windows

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#140]
Error message:

```
cts1_ground_support --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\CTS-SAT-1-OBC-Firmware\venv\Scripts\cts1_ground_support.exe\__main__.py", line 4, in <module>
  File "C:\CTS-SAT-1-OBC-Firmware\cts1_ground_support\src\cts1_ground_support\__init__.py", line 3, in <module>
    from cts1_ground_support.terminal_app.dash_gui import main
  File "C:\CTS-SAT-1-OBC-Firmware\cts1_ground_support\src\cts1_ground_support\terminal_app\dash_gui.py", line 139, in <module>
    for arg_num in range(get_max_arguments_per_telecommand())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CTS-SAT-1-OBC-Firmware\cts1_ground_support\src\cts1_ground_support\terminal_app\dash_gui.py", line 62, in get_max_arguments_per_telecommand
    telecommands = get_telecommand_list_from_repo_cached()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CTS-SAT-1-OBC-Firmware\cts1_ground_support\src\cts1_ground_support\terminal_app\dash_gui.py", line 41, in get_telecommand_list_from_repo_cached
    return parse_telecommand_list_from_repo()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CTS-SAT-1-OBC-Firmware\cts1_ground_support\src\cts1_ground_support\telecommand_array_parser.py", line 236, in parse_telecommand_list_from_repo
    c_files_concat: str = "\n".join(
                          ^^^^^^^^^^
  File "C:\CTS-SAT-1-OBC-Firmware\cts1_ground_support\src\cts1_ground_support\telecommand_array_parser.py", line 237, in <genexpr>
    f.read_text() for f in repo_path.glob("firmware/Core/Src/**/*.c")
    ^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1028, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 860: character maps to <undefined>
```

**Comment by DeflateAwning** [comment]
Credit to @robotoshi for finding and raising this!
